apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig

metadata:
  name: production-email-config
  namespace: monitoring

spec:
  route:
    receiver: email-notifications
    groupBy:
      - alertname
    groupWait: 10s
    groupInterval: 30s
    repeatInterval: 1m
    continue: true

  receivers:
    - name: email-notifications
      emailConfigs:
        - to: wolfcrew3240@gmail.com
          from: wolfcrew3240@gmail.com
          smarthost: smtp.gmail.com:587
          authUsername: wolfcrew3240@gmail.com
          authIdentity: wolfcrew3240@gmail.com
          authPassword:
            name: alertmanager-email-secret
            key: smtp-password
          requireTLS: true
          sendResolved: true