apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: production-devops-alerts
  namespace: production-devops
  labels:
    release: monitoring

spec:
  groups:
    - name: production-devops.rules
      rules:
        - alert: BackendDown
          expr: kube_deployment_status_replicas_available{namespace="production-devops",deployment="backend-deployment"} < 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Backend Deployment Down"
            description: "Backend deployment has no available replicas."

        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{namespace="production-devops",container!=""}[5m])) > 0.8
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU Usage"
            description: "CPU usage is above 80%."

        - alert: PodRestartingFrequently
          expr: increase(kube_pod_container_status_restarts_total{namespace="production-devops"}[10m]) > 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod Restarting Frequently"
            description: "A pod has restarted more than 3 times in the last 10 minutes."