apiVersion: v1
kind: Service

metadata:
  name: backend-service
  namespace: production-devops

spec:
  selector:
    app: backend
    project: production-devops

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: ClusterIP