apiVersion: v1
kind: Service

metadata:
  name: frontend-service
  namespace: staging

spec:
  selector:
    app: frontend
    project: staging

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
