name: Production DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Docker
        run: docker version

      - name: Verify Minikube
        shell: powershell
        run: |
          minikube status

      - name: Build Backend Image
        shell: powershell
        run: |
          docker build -t devops-backend:latest ./app/backend

      - name: Build Frontend Image
        shell: powershell
        run: |
          docker build -t devops-frontend:latest ./app/frontend

      - name: Load Images into Minikube
        shell: powershell
        run: |
          minikube image load devops-backend:latest
          minikube image load devops-frontend:latest

      - name: Deploy Namespace
        shell: powershell
        run: |
          kubectl apply -f k8s/namespace/

      - name: Deploy Backend
        shell: powershell
        run: |
          kubectl apply -f k8s/backend/

      - name: Deploy Frontend
        shell: powershell
        run: |
          kubectl apply -f k8s/frontend/

      - name: Deploy Ingress
        shell: powershell
        run: |
          kubectl apply -f k8s/ingress/

      - name: Wait for Backend Rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/backend-deployment -n production-devops --timeout=180s

      - name: Wait for Frontend Rollout
        shell: powershell
        run: |
          kubectl rollout status deployment/frontend-deployment -n production-devops --timeout=180s

      - name: Verify Pods
        shell: powershell
        run: |
          kubectl get pods -n production-devops